### ISSUE TITLE
Design Feedback

### ISSUE THREAD

**Issue by shin-sforzando** [hacking-papa/nuricame-web#26]
## Screenshots

(T.B.D.)

### Desktop (please complete the following information):

- [x] フッターのロゴから `https://hacking-papa.com` に飛ばない
  - OS: MacOS
  - Browser: Vivaldi
- [x] テキストの行間を1.5倍にしたい
  - OS: ??
  - Browser: ??
- [x] 緑色のボタンの大きさを現行の50%にしたい
  - OS: ??
  - Browser: ??
- [x] 各画像の大きさを50％縮小したい
  - OS: ??
  - Browser: ??
- [x] YouTube埋め込み動画の左右端を調整したい
  - OS: ??
  - Browser: ??
- [x] 「スマートフォンはこちら」と「お問い合わせはこちら」を揃えたい
  - OS: ??
  - Browser: ??

### Smartphone (please complete the following information):

![nurikame_pc_0425](https://user-images.githubusercontent.com/32637762/80279988-f6b37e00-873b-11ea-8881-60d8a0ca0a59.png)

- [x] 文字が大きくなりすぎて意図せぬ位置で改行される
  - Device: iPhone XS
  - Browser: Safari
- [x] Loadingの文字色が白い
  - OS: iPhone??
  - Browser: Safari??
- [x] アップロードのモーダルで下部のボタンがずれている
  - OS: iPhone??
  - Browser: Safari??
- [x] 最上部、はっきんぐパパのロゴを70％にしたい
  - OS: iPhone??
  - Browser: Safari??
- [x] 上部、ぬりカメのロゴを120％にして、はっきんぐパパのロゴに寄せる
  - OS: iPhone??
  - Browser: Safari??
- [x] テキストの行間を1.5倍にしたい
  - OS: iPhone??
  - Browser: Safari??
- [x] 緑色のボタンの大きさを現行の50%にしたい
  - OS: iPhone??
  - Browser: Safari??
- [x] 「ぬりえを作る」section前の余白を現行の60％にしたい
  - OS: iPhone??
  - Browser: Safari??
- [x] 「ぬりえを作る」ボタンの下に注釈を入れたい
  - OS: iPhone??
  - Browser: Safari??
- [x] 「ぬりカメとは」section内h2の上下余白を現行の60％にしたい
  - OS: iPhone??
  - Browser: Safari??
- [x] YouTube埋め込み動画前の余白を60%にしたい
  - OS: iPhone??
  - Browser: Safari??
- [x] YouTube埋め込み動画の縦中央が揃っていない
  - OS: iPhone??
  - Browser: Safari??
- [x] YouTube埋め込み動画下の余白を現行の60%にしたい
  - OS: iPhone??
  - Browser: Safari??
- [x] YouTube埋め込み動画下の余白を現行の60%にしたい
  - OS: iPhone??
  - Browser: Safari??
- [x] 「ぬりカメ1号機」注釈の上余白を現行の50%にしたい
  - OS: iPhone??
  - Browser: Safari??
- [x] 「ぬりカメ1号機」注釈の下余白を現行の60%にしたい
  - OS: iPhone??
  - Browser: Safari??
- [x] 「ぬりえしてる様子」画像を横幅いっぱいにしたい
  - OS: iPhone??
  - Browser: Safari??
- [x] 最下部はっきんぐパパロゴを現行の50%にしたい
  - OS: iPhone??
  - Browser: Safari??
- [x] 【PC_結果ページ】
結果の塗り絵化フレームが背面カラーと馴染んでみえるのでグレーの罫線を囲む
（罫線のグレー色：#787878、太さは塗り絵と同じくらいの太さでお願いします）
    - OS: iPhone
    - Browser: chrome
- [x] 【PC_結果ページ】
トップへ戻る緑ボタンがPCだと大きく表示されてるので　40%縮小 
    - OS: iPhone
    - Browser: chrome

- [x] 【PC_トップページ】
FVのぬりかめロゴを150%拡大して少し上にあげてください。
- Browser: chrome

## Additional context

2020/04/26 12:19、更新。

**Comment by HighBigSun** [comment]
【スマホ】
ぬりえにしています。ちょっと待ってね
が黄色が明るすぎて白字が見にくいです

**Comment by kurohakodai** [comment]
【PC】
ロゴなどはまだ入っていない感じですかね？？
塗り絵化はうまくいきました！

**Comment by HighBigSun** [comment]
【スマホ】
全体：娘、息子共に一度やり方を教えたら塗り絵化はできました。最初のレクチャーが必要ですが、保存までは一人でできます。

アップロード時：これで塗り絵を作る　の緑のボタンがずれています（ダミーポスト
というボタンがあるからですかね？？）

**Comment by kurohakodai** [comment]
[SP0425.pdf](https://github.com/hacking-papa/nuricame-web/files/4532868/SP0425.pdf)
【スマホ】

**Comment by kurohakodai** [comment]
【PC版】

1.FVのぬりかめロゴを上に上げる（右上のはっきんぐパパロゴの高さ分ほど）

2.コンセプトコピー（外出できなくて、〜〜）の行間を今の倍空ける（SP修正と同様の指示です）

3.緑のボタンが大きいので50%縮小

4.緑のボタン下の※注釈はトル（PCでは取るんですよね？？）

5.使い方のサルの元写真画像、塗り絵化画像、プリンター画像が大きいので50%縮小

6.動画が左右端が切れているので調整

7.ぬりかめ1号機の画像70%に縮小

8.『スマートフォンはこちら』のURLを『おといあわせはこちら』のアドレスに高さ揃える
（QR画像少し小さくしないとダメですかね？？）

**Comment by kurohakodai** [comment]
【PC_結果ページ】スクショ添付します。
![nurikame_PC_result_0426_1](https://user-images.githubusercontent.com/63997824/80296507-e5f41e00-87b6-11ea-9cbf-c2bfaa77d054.png)

1.結果の塗り絵化フレームが背面カラーと馴染んでみえるのでグレーの罫線を囲む
（罫線のグレー色：#787878、太さは塗り絵の囲みと同じくらいの太さでお願いします）
2.トップへ戻る緑ボタンがPCだと大きく表示されてるので40%縮小
【スマホ_結果ページ】
デザインOKです。

**Comment by kurohakodai** [comment]
【PC】スクショ添付します。
FVのぬりかめロゴを150%拡大して少し上にあげてください。
添付の赤囲みがイメージの位置です。
![nurikame_PC_top_0426_2](https://user-images.githubusercontent.com/63997824/80302216-ae4f9b00-87e3-11ea-9b1b-5590a5f226cc.jpg)

**Comment by shinyaaman** [comment]
**【SP/PC共通】文字周りUpdate**
すみません、改めて使ってみて文字周り気になってしまい、修正いただけると幸いです。

＜トップページ：ステートメント＞
- 好きなものをなんでもカメラで　→ 好きなものをなんでも
- すべての子どもたちに無料公開　→ 無料公開

＜完了ページ：ぬりえ画像下＞
- ダウンロードして印刷しよう！　→ 上の画像を保存して印刷しよう！
- #ぬりカメでぬりえ　→ [#ぬりカメでぬりえ](https://twitter.com/search?q=%23%E3%81%AC%E3%82%8A%E3%82%AB%E3%83%A1%E3%81%A7%E3%81%AC%E3%82%8A%E3%81%88)

**【SP】デザインbug（公開後修正でも構いません。）**
- ローディングマークが出ない。

![IMG_05AD69826F65-1](https://user-images.githubusercontent.com/3088135/80305194-58d0b980-87f6-11ea-9387-14f34a8966df.jpeg)

- 完了ページの右端に余白あり。

![IMG_2184](https://user-images.githubusercontent.com/3088135/80305207-6b4af300-87f6-11ea-88a3-b042919b0c00.PNG)
